### ISSUE TITLE
Meta Devlopment

### ISSUE THREAD

**Issue by Techterror12** [ThyCorp/Animidolorem#2]
- [x] Layout Meta Plan ODT Doc
- [ ] Finish Meta Plan
- [ ] Layout Graphs for Meta Value Files
- [ ] Have Meetings
